//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToysStores
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public Nullable<long> Size { get; set; }
        public string StoreOwner { get; set; }
        public Nullable<long> ToysCount { get; set; }
    }
}
